"""Alembic script template."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers
revision = "57d5baa11a87"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('related_entity_id', sa.UUID(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=64), nullable=True),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('progress_message', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_status', 'processing_jobs', ['status'], unique=False)
    op.create_index('ix_job_type', 'processing_jobs', ['job_type'], unique=False)
    op.create_table('provenance_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('operation', sa.String(length=128), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('operator', sa.String(length=128), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provenance_entity', 'provenance_records', ['entity_id', 'entity_type'], unique=False)
    op.create_index('ix_provenance_operation', 'provenance_records', ['operation'], unique=False)
    op.create_index('ix_provenance_recorded_at', 'provenance_records', ['recorded_at'], unique=False)
    op.create_table('scenes',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('source_path', sa.String(length=2048), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('file_checksum', sa.String(length=64), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('sensor', sa.String(length=128), nullable=True),
    sa.Column('platform', sa.String(length=128), nullable=True),
    sa.Column('product_type', sa.String(length=128), nullable=True),
    sa.Column('acquisition_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acquisition_date_str', sa.String(length=64), nullable=True),
    sa.Column('crs_wkt', sa.Text(), nullable=True),
    sa.Column('crs_epsg', sa.Integer(), nullable=True),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('num_bands', sa.Integer(), nullable=True),
    sa.Column('band_descriptions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolution_x_m', sa.Float(), nullable=True),
    sa.Column('resolution_y_m', sa.Float(), nullable=True),
    sa.Column('nodata_value', sa.Float(), nullable=True),
    sa.Column('footprint', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('bbox_west', sa.Float(), nullable=True),
    sa.Column('bbox_south', sa.Float(), nullable=True),
    sa.Column('bbox_east', sa.Float(), nullable=True),
    sa.Column('bbox_north', sa.Float(), nullable=True),
    sa.Column('cloud_cover_pct', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('quality_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingestion_status', sa.String(length=32), server_default='PENDING', nullable=False),
    sa.Column('ingestion_error', sa.Text(), nullable=True),
    sa.Column('tile_count', sa.Integer(), nullable=False),
    sa.Column('embedded_count', sa.Integer(), nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("ingestion_status IN ('PENDING','PROCESSING','COMPLETED','FAILED')", name='ck_scene_status'),
    sa.CheckConstraint('cloud_cover_pct IS NULL OR (cloud_cover_pct >= 0 AND cloud_cover_pct <= 100)', name='ck_cloud_cover_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scene_acquisition_date', 'scenes', ['acquisition_date'], unique=False)
    op.create_index('ix_scene_sensor', 'scenes', ['sensor'], unique=False)
    op.create_index('ix_scene_status', 'scenes', ['ingestion_status'], unique=False)
    op.create_table('tiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=False),
    sa.Column('tile_col', sa.Integer(), nullable=False),
    sa.Column('tile_row', sa.Integer(), nullable=False),
    sa.Column('tile_size', sa.Integer(), nullable=False),
    sa.Column('pixel_x_off', sa.Integer(), nullable=False),
    sa.Column('pixel_y_off', sa.Integer(), nullable=False),
    sa.Column('pixel_width', sa.Integer(), nullable=False),
    sa.Column('pixel_height', sa.Integer(), nullable=False),
    sa.Column('footprint', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('center_lon', sa.Float(), nullable=True),
    sa.Column('center_lat', sa.Float(), nullable=True),
    sa.Column('bbox_west', sa.Float(), nullable=True),
    sa.Column('bbox_south', sa.Float(), nullable=True),
    sa.Column('bbox_east', sa.Float(), nullable=True),
    sa.Column('bbox_north', sa.Float(), nullable=True),
    sa.Column('tile_path', sa.String(length=2048), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=2048), nullable=True),
    sa.Column('acquisition_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sensor', sa.String(length=128), nullable=True),
    sa.Column('resolution_m', sa.Float(), nullable=True),
    sa.Column('cloud_cover_pct', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('nodata_ratio', sa.Float(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('remoteclip_vector_id', sa.String(length=128), nullable=True),
    sa.Column('dino_vector_id', sa.String(length=128), nullable=True),
    sa.Column('embedding_model', sa.String(length=128), nullable=True),
    sa.Column('embedded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tile_acquisition_date', 'tiles', ['acquisition_date'], unique=False)
    op.create_index('ix_tile_embedded', 'tiles', ['remoteclip_vector_id'], unique=False)
    op.create_index('ix_tile_quality', 'tiles', ['quality_score'], unique=False)
    op.create_index('ix_tile_scene_id', 'tiles', ['scene_id'], unique=False)
    op.create_index('ix_tile_sensor', 'tiles', ['sensor'], unique=False)
    op.create_table('change_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('before_tile_id', sa.UUID(), nullable=True),
    sa.Column('after_tile_id', sa.UUID(), nullable=True),
    sa.Column('before_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('after_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('earliest_supported_observation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('temporal_persistence_count', sa.Integer(), nullable=False),
    sa.Column('aoi_footprint', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('center_lon', sa.Float(), nullable=True),
    sa.Column('center_lat', sa.Float(), nullable=True),
    sa.Column('change_type', sa.String(length=64), nullable=True),
    sa.Column('final_confidence', sa.Float(), nullable=True),
    sa.Column('visual_change_score', sa.Float(), nullable=True),
    sa.Column('semantic_change_score', sa.Float(), nullable=True),
    sa.Column('spectral_change_score', sa.Float(), nullable=True),
    sa.Column('registration_quality', sa.Float(), nullable=True),
    sa.Column('temporal_persistence_score', sa.Float(), nullable=True),
    sa.Column('cloud_penalty', sa.Float(), nullable=True),
    sa.Column('shadow_penalty', sa.Float(), nullable=True),
    sa.Column('seasonal_penalty', sa.Float(), nullable=True),
    sa.Column('confidence_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_suppressed', sa.Boolean(), nullable=False),
    sa.Column('suppression_reason', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("review_status IN ('PENDING','CONFIRMED','REJECTED','NEEDS_REVIEW')", name='ck_change_review_status'),
    sa.CheckConstraint('final_confidence IS NULL OR (final_confidence >= 0 AND final_confidence <= 1)', name='ck_confidence_range'),
    sa.ForeignKeyConstraint(['after_tile_id'], ['tiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['before_tile_id'], ['tiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_change_after_date', 'change_events', ['after_date'], unique=False)
    op.create_index('ix_change_before_date', 'change_events', ['before_date'], unique=False)
    op.create_index('ix_change_confidence', 'change_events', ['final_confidence'], unique=False)
    op.create_index('ix_change_review_status', 'change_events', ['review_status'], unique=False)
    op.create_index('ix_change_type', 'change_events', ['change_type'], unique=False)
    op.create_table('feedback_signals',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tile_id', sa.UUID(), nullable=True),
    sa.Column('signal_type', sa.String(length=32), nullable=False),
    sa.Column('context', sa.String(length=256), nullable=True),
    sa.Column('analyst_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("signal_type IN ('POSITIVE','NEGATIVE')", name='ck_signal_type'),
    sa.ForeignKeyConstraint(['tile_id'], ['tiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyst_decisions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('change_event_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('corrected_change_type', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('analyst_id', sa.String(length=128), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('CONFIRMED','REJECTED','NEEDS_REVIEW')", name='ck_analyst_decision'),
    sa.ForeignKeyConstraint(['change_event_id'], ['change_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyst_decisions')
    op.drop_table('feedback_signals')
    op.drop_index('ix_change_type', table_name='change_events')
    op.drop_index('ix_change_review_status', table_name='change_events')
    op.drop_index('ix_change_confidence', table_name='change_events')
    op.drop_index('ix_change_before_date', table_name='change_events')
    op.drop_index('ix_change_aoi', table_name='change_events', postgresql_using='gist')
    op.drop_index('ix_change_after_date', table_name='change_events')
    op.drop_index('idx_change_events_aoi_footprint', table_name='change_events', postgresql_using='gist')
    op.drop_table('change_events')
    op.drop_index('ix_tile_sensor', table_name='tiles')
    op.drop_index('ix_tile_scene_id', table_name='tiles')
    op.drop_index('ix_tile_quality', table_name='tiles')
    op.drop_index('ix_tile_footprint', table_name='tiles', postgresql_using='gist')
    op.drop_index('ix_tile_embedded', table_name='tiles')
    op.drop_index('ix_tile_acquisition_date', table_name='tiles')
    op.drop_index('idx_tiles_footprint', table_name='tiles', postgresql_using='gist')
    op.drop_table('tiles')
    op.drop_index('ix_scene_status', table_name='scenes')
    op.drop_index('ix_scene_sensor', table_name='scenes')
    op.drop_index('ix_scene_footprint', table_name='scenes', postgresql_using='gist')
    op.drop_index('ix_scene_acquisition_date', table_name='scenes')
    op.drop_index('idx_scenes_footprint', table_name='scenes', postgresql_using='gist')
    op.drop_table('scenes')
    op.drop_index('ix_provenance_recorded_at', table_name='provenance_records')
    op.drop_index('ix_provenance_operation', table_name='provenance_records')
    op.drop_index('ix_provenance_entity', table_name='provenance_records')
    op.drop_table('provenance_records')
    op.drop_index('ix_job_type', table_name='processing_jobs')
    op.drop_index('ix_job_status', table_name='processing_jobs')
    op.drop_table('processing_jobs')
    # ### end Alembic commands ###
